### ISSUE TITLE
Duplicated letters not accounted for correctly

### ISSUE THREAD

**Issue by tatref** [billthefarmer/gurgle#14]
If a letter appear multiple times, it may show up yellow, even if duplicates are all on correct places:

![image](https://user-images.githubusercontent.com/2582791/154876323-65c9876d-b43e-4f07-991a-971b07bdedaa.png)

The last `A` on 1st and 2nd line should be gray, because other occurrences are already used.

**Comment by billthefarmer** [comment]
There are several points &ndash; I am not aware of the concept of a letter being 'used'. The letter 'A' is in the word but in the wrong place. The language in your screenshot is shown as French. I have not released a French version because there are 134,000 odd words in the Lexica French dictionary which would make the game ridiculously difficult. The word 'abajo' is Spanish, AFAIK.

If you have forked the app and added a French dictionary you ought to share it. Also raising an issue on a forked version of an app is contentious.

**Comment by tatref** [comment]
I am currently adding support for french in the app, and I will submit a proper PR when done. Also, the game in french is not hard.
However, I find it cumbersome to add languages as .java files, so I am trying to store word lists in external files

About the issue, you can find details here: https://nerdschalk.com/wordle-same-letter-twice-rules-explained-how-does-it-work/
See the last image with letter `E` in the second row.

**Comment by billthefarmer** [comment]
There is code for loading dictionaries in the background in my [Crossword](https://github.com/billthefarmer/crossword) app. This app doesn't pretend to be a Wordle clone, it just looks like it. If you think it should work differently, fix it in your PR.

**Comment by acheronfail** [comment]
+1 to handling double letters the way the above link describes! I just had a really tough time guessing CLOWN because I'd guessed LOONY before and both O's were highlighted (one was green and the other yellow). 

I think most people come to this from Wordle (or its derivatives) and mimicking the behaviour would be a plus in my eyes. 🙂

**Comment by billthefarmer** [comment]
OK, that will be in the next version
